- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    vsphere_url: "{{ url }}"
    vsphere_url_sdk: "https://{{ url }}/sdk"
    vsphere_username: "{{ username }}"
    vsphere_password: "{{ password }}"
    validator_output_file_name: "/tmp/output.json"
    gather_information_output_file_name: "/tmp/infra.json"
    aggregated_report_output_file_name: "/tmp/inventory.json"

  roles:
    - name: Run gather information
      role: gather_information
      vars:
        gather_information_vsphere_hostname: "{{ vsphere_url }}"
        gather_information_vsphere_username: "{{ vsphere_username }}"
        gather_information_vsphere_password: "{{ vsphere_password }}"
        gather_information_vsphere_validate_certs: false

    - name: Run virtual machine validator
      role: validator
      vars:
        validator_vsphere_server: "{{ vsphere_url_sdk }}"
        validator_vsphere_username: "{{ vsphere_username }}"
        validator_vsphere_password: "{{ vsphere_password }}"

  tasks:
    - name: Run Python script to aggregate VM data
      command: "python3 aggregate_data.py {{ gather_information_output_file_name }} {{ validator_output_file_name }} {{ aggregated_report_output_file_name }}"
